import Link from "next/link";
import { getCurrentActor } from "@/server/auth";
import { listQuestions } from "@/services/question.service";
import { AdminEmpty, AdminPageHeader, Status } from "@/components/admin/admin-ui";

export default async function QuestionsPage({ searchParams }: { searchParams: Promise<{ query?: string; status?: "DRAFT" | "IN_REVIEW" | "PUBLISHED" | "ARCHIVED" }> }) {
  const actor = await getCurrentActor(); if (!actor) return null;
  const filters = await searchParams; const result = await listQuestions(actor, { query: filters.query, status: filters.status, pageSize: 50 });
  return <div className="mx-auto max-w-6xl p-4 sm:p-6 lg:p-8"><AdminPageHeader title="คลังคำถาม" description="ค้นหาและตรวจสถานะคำถามก่อนนำไปใช้ในแบบประเมิน" /><form className="mt-6 flex flex-col gap-3 sm:flex-row"><label className="sr-only" htmlFor="query">ค้นหาคำถาม</label><input id="query" name="query" defaultValue={filters.query} placeholder="ค้นหาจากข้อความคำถาม" className="min-h-11 flex-1 rounded-md border border-[var(--border)] bg-[var(--surface)] px-3 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus-ring)]" /><select name="status" defaultValue={filters.status ?? ""} className="min-h-11 rounded-md border border-[var(--border)] bg-[var(--surface)] px-3"><option value="">ทุกสถานะ</option><option value="DRAFT">ฉบับร่าง</option><option value="IN_REVIEW">รอตรวจทาน</option><option value="PUBLISHED">เผยแพร่แล้ว</option></select><button className="min-h-11 rounded-md bg-[var(--primary)] px-4 text-sm font-semibold text-[var(--primary-foreground)]">ค้นหา</button>{(filters.query || filters.status) ? <Link href="/admin/questions" className="inline-flex min-h-11 items-center justify-center px-3 text-sm font-semibold underline">ล้างตัวกรอง</Link> : null}</form>{result.items.length ? <div className="mt-6"><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="border-y border-[var(--border)] text-[var(--muted-foreground)]"><tr><th className="p-3">คำถาม</th><th className="p-3">ประเภท</th><th className="p-3">ความยาก</th><th className="p-3">สถานะ</th><th className="p-3">แนวคิด</th></tr></thead><tbody>{result.items.map((question) => <tr key={question.id} className="border-b border-[var(--border)]"><td className="max-w-md p-3">{question.prompt}</td><td className="p-3">{question.type}</td><td className="p-3">{question.difficulty}/5</td><td className="p-3"><Status value={question.status} /></td><td className="p-3">{question.concepts.map((concept) => concept.title).join(", ") || "—"}</td></tr>)}</tbody></table></div><ul className="divide-y divide-[var(--border)] md:hidden">{result.items.map((question) => <li key={question.id} className="py-4"><p className="font-medium">{question.prompt}</p><div className="mt-2 flex flex-wrap items-center gap-2 text-sm text-[var(--muted-foreground)]"><span>{question.type}</span><span>ระดับ {question.difficulty}/5</span><Status value={question.status} /></div></li>)}</ul></div> : <div className="mt-6"><AdminEmpty type="question" title="ไม่พบคำถาม" description="ลองล้างตัวกรองหรือเพิ่มคำถามใหม่เพื่อเริ่มต้นคลังคำถาม" /></div>}</div>;
}
