import Link from "next/link";
import { ChartNoAxesColumn, CircleAlert } from "lucide-react";
import { logoutAction } from "@/app/actions/auth.actions";
import { ContinueLearning } from "@/components/learning/continue-learning";
import { AvailableCourses } from "@/components/learning/available-courses";
import { StatusBadge } from "@/components/ui/status-badge";
import { getCurrentActor } from "@/server/auth";
import { getLearnerDashboard } from "@/services/learner.service";

export default async function Home() {
  const actor = await getCurrentActor();
  if (!actor) return <main className="mx-auto flex min-h-dvh w-full max-w-3xl items-center px-5 py-10"><section className="w-full border border-[var(--border)] bg-[var(--surface)] p-6 sm:p-10"><p className="text-sm font-medium text-[var(--primary)]">Personal Learning OS</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">เรียนรู้ตามจังหวะของคุณ</h1><p className="mt-3 text-[var(--muted-foreground)]">สร้างบัญชีเพื่อเริ่มเรียนและบันทึกความก้าวหน้า</p><div className="mt-8 flex flex-wrap gap-3"><Link className="inline-flex min-h-11 items-center rounded-md bg-[var(--primary)] px-4 text-sm font-medium text-[var(--primary-foreground)]" href="/register">สร้างบัญชี</Link><Link className="inline-flex min-h-11 items-center rounded-md border border-[var(--border)] px-4 text-sm font-medium" href="/login">เข้าสู่ระบบ</Link></div></section></main>;
  const dashboard = await getLearnerDashboard(actor);
  return <div className="min-h-dvh bg-[var(--background)]"><header className="border-b border-[var(--border)] bg-[var(--surface)]"><div className="mx-auto flex min-h-16 max-w-6xl items-center justify-between gap-4 px-4 sm:px-6"><Link className="font-semibold" href="/">Personal Learning OS</Link><form action={logoutAction}><button className="min-h-11 rounded-md px-3 text-sm font-medium">ออกจากระบบ</button></form></div></header><main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 sm:py-12">
    {dashboard.continueItem ? <><ContinueLearning item={dashboard.continueItem} /><section aria-labelledby="courses-heading" className="mt-10"><h2 id="courses-heading" className="text-xl font-semibold">หลักสูตรของฉัน</h2><ul className="mt-4 divide-y divide-[var(--border)] border-y border-[var(--border)]">{dashboard.courses.map((course) => <li key={course.slug} className="py-4"><Link className="block rounded-lg px-2 py-2 hover:bg-[var(--surface-subtle)]" href={`/courses/${course.slug}`}><div className="flex items-center justify-between gap-4"><div><h3 className="font-semibold">{course.title}</h3>{course.description ? <p className="mt-1 text-sm text-[var(--muted-foreground)]">{course.description}</p> : null}</div><span className="shrink-0 text-sm font-medium">{course.progress.percent}%</span></div><p className="mt-2 text-sm text-[var(--muted-foreground)]">เรียนจบ {course.progress.completedLessons} จาก {course.progress.totalLessons} บท</p></Link></li>)}</ul></section></> : null}
    <AvailableCourses courses={dashboard.availableCourses} />
    <div className="mt-10 grid gap-10 lg:grid-cols-2"><section aria-labelledby="recent-result-heading"><div className="flex items-center gap-2"><ChartNoAxesColumn className="size-5 text-[var(--primary)]" aria-hidden="true" /><h2 id="recent-result-heading" className="text-lg font-semibold">ผลล่าสุด</h2></div>{dashboard.recentResult ? <div className="mt-4 border-l-2 border-[var(--primary)] pl-4"><p className="font-medium">{dashboard.recentResult.assessment.title}</p><p className="mt-1 text-sm text-[var(--muted-foreground)]">คะแนน {dashboard.recentResult.percentage ?? 0}%</p><StatusBadge className="mt-3" variant={dashboard.recentResult.passed ? "success" : "warning"}>{dashboard.recentResult.passed ? "ผ่าน" : "ควรทบทวนเพิ่ม"}</StatusBadge></div> : <p className="mt-4 text-sm text-[var(--muted-foreground)]">เมื่อทำแบบประเมินแล้ว ผลล่าสุดจะแสดงที่นี่</p>}</section><section aria-labelledby="weak-heading"><div className="flex items-center gap-2"><CircleAlert className="size-5 text-[var(--warning)]" aria-hidden="true" /><h2 id="weak-heading" className="text-lg font-semibold">หัวข้อที่ควรฝึกเพิ่ม</h2></div>{dashboard.weakConcepts.length ? <ul className="mt-4 space-y-3">{dashboard.weakConcepts.map((concept) => <li key={concept.conceptId}><p className="font-medium">{concept.title}</p><p className="text-sm text-[var(--muted-foreground)]">ความเข้าใจ {concept.masteryPercent}%</p></li>)}</ul> : <p className="mt-4 text-sm text-[var(--muted-foreground)]">ยังไม่มีหัวข้อที่ต้องทบทวนเป็นพิเศษ</p>}</section></div>
  </main></div>;
}
