"use client";

import { useState } from "react";
import { upsertLessonBlocksAction } from "@/app/actions/lesson.actions";

export function LessonEditor({ lesson }: { lesson: { id: string; blocks: Array<{ id: string; type: string; contentMarkdown: string | null; position: number }> } }) {
  const [blocks, setBlocks] = useState(lesson.blocks); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false);
  const move = (index: number, direction: -1 | 1) => { const target = index + direction; if (target < 0 || target >= blocks.length) return; const next = [...blocks]; [next[index], next[target]] = [next[target], next[index]]; setBlocks(next.map((block, position) => ({ ...block, position }))); };
  const submit = async (formData: FormData) => { setPending(true); const result = await upsertLessonBlocksAction(lesson.id, formData); setError(result.success ? null : result.error ?? "ไม่สามารถบันทึกเนื้อหาได้"); setPending(false); };
  return <form action={submit}><input type="hidden" name="blocks" value={JSON.stringify(blocks.map(({ type, contentMarkdown, position }) => ({ type, contentMarkdown, position })))} /><div className="space-y-4">{blocks.map((block, index) => <article key={block.id} className="border border-[var(--border)] p-4"><div className="flex items-center justify-between gap-3"><strong className="text-sm">{block.type}</strong><div className="flex gap-1"><button type="button" onClick={() => move(index, -1)} disabled={index === 0} className="min-h-11 rounded-md px-3 text-sm underline disabled:opacity-50">ขึ้น</button><button type="button" onClick={() => move(index, 1)} disabled={index === blocks.length - 1} className="min-h-11 rounded-md px-3 text-sm underline disabled:opacity-50">ลง</button></div></div><label className="sr-only" htmlFor={`block-${block.id}`}>เนื้อหา {block.type}</label><textarea id={`block-${block.id}`} value={block.contentMarkdown ?? ""} onChange={(event) => setBlocks(blocks.map((item) => item.id === block.id ? { ...item, contentMarkdown: event.target.value } : item))} rows={5} className="mt-3 w-full rounded-md border border-[var(--border)] bg-[var(--surface)] p-3 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus-ring)]" /></article>)}</div>{!blocks.length ? <p className="text-sm text-[var(--muted-foreground)]">ยังไม่มี content block ในบทเรียนนี้</p> : null}{error ? <p role="alert" className="mt-4 text-sm text-[var(--danger)]">{error}</p> : null}<button type="submit" disabled={pending} className="mt-5 min-h-11 rounded-md bg-[var(--primary)] px-4 text-sm font-semibold text-[var(--primary-foreground)] disabled:opacity-60">{pending ? "กำลังบันทึก…" : "บันทึก content blocks"}</button></form>;
}
