"use client";

import { useState } from "react";
import { createMcpClientAction, revokeMcpClientAction } from "@/app/actions/admin.actions";
import { Dialog } from "@/components/ui/dialog";

const permissions = ["course:read", "course:write", "lesson:read", "lesson:write", "question:read", "question:write", "assessment:read", "assessment:write", "analytics:read", "source:read", "source:write"] as const;

export function McpClientManager({ clients }: { clients: Array<{ id: string; name: string; permissions: string[]; revokedAt: Date | null; lastUsedAt: Date | null }> }) {
  const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false); const [token, setToken] = useState<string | null>(null); const [revokeId, setRevokeId] = useState<string | null>(null);
  const submit = async (formData: FormData) => { setPending(true); const data = new FormData(); data.set("data", JSON.stringify({ name: formData.get("name"), permissions: formData.getAll("permissions") })); const result = await createMcpClientAction(data); if (result.success) { setToken(result.data.token); setError(null); } else setError(result.error); setPending(false); };
  return <><section className="grid gap-5 border border-[var(--border)] p-5"><h2 className="text-lg font-semibold">สร้าง MCP client</h2><form action={submit} className="grid gap-4"><label className="grid gap-1.5 text-sm font-medium">ชื่อ client<input name="name" required className="min-h-11 rounded-md border border-[var(--border)] bg-[var(--surface)] px-3" /></label><fieldset><legend className="text-sm font-medium">สิทธิ์ที่อนุญาต</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{permissions.map((permission) => <label key={permission} className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" name="permissions" value={permission} />{permission}</label>)}</div></fieldset>{error ? <p role="alert" className="text-sm text-[var(--danger)]">{error}</p> : null}<button type="submit" disabled={pending} className="min-h-11 w-fit rounded-md bg-[var(--primary)] px-4 text-sm font-semibold text-[var(--primary-foreground)] disabled:opacity-60">{pending ? "กำลังสร้าง…" : "สร้าง token"}</button></form></section><ul className="mt-8 divide-y divide-[var(--border)] border-y border-[var(--border)]">{clients.map((client) => <li key={client.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">{client.name}</h2><p className="mt-1 text-sm text-[var(--muted-foreground)]">{client.permissions.join(", ")}</p><p className="mt-1 text-xs text-[var(--muted-foreground)]">ใช้งานล่าสุด: {client.lastUsedAt?.toLocaleString("th-TH") ?? "ยังไม่เคยใช้งาน"}</p></div>{client.revokedAt ? <span className="text-sm font-semibold text-[var(--danger)]">เพิกถอนแล้ว</span> : <button type="button" onClick={() => setRevokeId(client.id)} className="min-h-11 rounded-md border border-[var(--danger)] px-4 text-sm font-semibold text-[var(--danger)]">เพิกถอน</button>}</li>)}</ul><Dialog isOpen={token !== null} onClose={() => setToken(null)} title="บันทึก token นี้ทันที"><p className="text-sm text-[var(--muted-foreground)]">Token จะแสดงเพียงครั้งนี้เท่านั้น และจะไม่ปรากฏอีกในระบบ</p><code className="mt-4 block break-all rounded-md bg-[var(--surface-subtle)] p-3 text-sm">{token}</code></Dialog><Dialog isOpen={revokeId !== null} onClose={() => setRevokeId(null)} title="เพิกถอน MCP client"><p className="text-sm text-[var(--muted-foreground)]">Client นี้จะไม่สามารถใช้ token เดิมได้อีก</p><div className="mt-5 flex gap-3"><button type="button" onClick={async () => { if (revokeId) await revokeMcpClientAction(revokeId); setRevokeId(null); }} className="min-h-11 rounded-md bg-[var(--danger)] px-4 text-sm font-semibold text-white">เพิกถอน client</button><button type="button" onClick={() => setRevokeId(null)} className="min-h-11 rounded-md border border-[var(--border)] px-4 text-sm font-semibold">ยกเลิก</button></div></Dialog></>;
}
